version: "3.8"
services:
  mongo:
    image: mongo
    container_name: mongo_c
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - trademe-network
  api:
    build: ./api
    container_name: api_c
    ports:
      - "4000:4000"
    depends_on:
      - mongo
    volumes:
      - ./api:/app
    environment:
      - MONGO_URL=mongodb://mongo:27017/mydb
    networks:
      - trademe-network
  # client:
  #   build: ./client
  #   container_name: client_c
  #   ports:
  #     - "3000:3000"
  #   stdin_open: true
  #   tty: true
  #   depends_on:
  #     - api
  #   volumes:
  #     - ./client:/app
  #     - /client/node_modules
  trademe:
    build: ./trademe
    container_name: trademe_c
    ports:
      - "5173:5173"
    depends_on:
      - api
    # volumes:
    #   - ./trademe:/app
    #   # - /trademe/node_modules
volumes:
  mongo-data:

networks:
  trademe-network:
    driver: bridge